global:
  wildcardDomain: apps.cluster.example.com
  toolsImage: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest

gateways:
  maasDefaultGateway:
    create: true
    useRoute: true
  openshiftAiInference:
    create: true
    useRoute: true

dataScienceCluster:
  create: true
  components:
    aipipelines:
      argoWorkflowsControllers:
        managementState: Removed
      managementState: Removed
    dashboard:
      managementState: Managed
    feastoperator:
      managementState: Removed
    kserve:
      nim:
        managementState: Removed
      modelsAsService:
        managementState: Managed
      rawDeploymentServiceConfig: Headless
      managementState: Managed
    kueue:
      defaultClusterQueueName: default
      defaultLocalQueueName: default
      managementState: Removed
    llamastackoperator:
      managementState: Managed
    mlflowoperator:
      managementState: Removed
    modelregistry:
      registriesNamespace: rhoai-model-registries
      managementState: Managed
    ray:
      managementState: Removed
    trainingoperator:
      managementState: Removed
    trustyai:
      eval:
        lmeval:
          permitCodeExecution: deny
          permitOnline: deny
      managementState: Managed
    workbenches:
      workbenchNamespace: rhods-notebooks
      managementState: Managed

rhcl:
  create: true
  namespace: kuadrant-system

lws:
  create: true

install-operators:
  enabled: true
  operators:
    devspaces:
      enabled: true
      channel: stable

    openshift-cert-manager-operator:
      enabled: true
      channel: stable-v1
      namespace: cert-manager-operator
      operatorGroup:
        enabled: true

    leader-worker-set:
      enabled: true
      channel: stable-v1.0
      namespace: openshift-lws-operator
      operatorGroup:
        enabled: true
      targetNamespaces:
        - openshift-lws-operator

    grafana-operator:
      enabled: true
      channel: v5
      catalog: community-operators

    rhods-operator:
      enabled: true
      channel: stable-3.3
      installPlanApproval: Manual
      startingCSV: rhods-operator.3.3.0
      namespace: redhat-ods-operator
      operatorGroup:
        enabled: true

    rhcl-operator:
      enabled: true
      channel: stable

    cloudnative-pg:
      enabled: true
      channel: stable-v1
      catalog: certified-operators

    rhbk-operator:
      enabled: true
      channel: stable-v26.4
      namespace: keycloak
      operatorGroup:
        enabled: true
      targetNamespaces:
        - keycloak
