---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "maas-code-assistant.labels" . | nindent 4 }}
    config.openshift.io/inject-trusted-cabundle: "true"
  name: ocp-injected-certs
  namespace: {{ .Values.namespace }}
