apiVersion: v1
kind: Secret
metadata:
  name: grafana-proxy
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "maas-code-assistant.labels" . | nindent 4 }}
data:
  {{- $old_sec := lookup "v1" "Secret" .Values.namespace "grafana-proxy" }}
  {{- if .Values.sessionSecret }}
  session_secret: {{ .Values.sessionSecret }}
  {{- else if or (not $old_sec) (not $old_sec.data) }}
  session_secret: {{ randAlphaNum 20 | b64enc }}
  {{ else }}
  session_secret: {{ index $old_sec.data "session_secret" }}
  {{ end }}
type: Opaque
