{{- with .Values.gateways.maasDefaultGateway }}
{{- if .create }}
{{- if .useRoute }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-default-gateway-config
  namespace: openshift-ingress
data:
  service: |
    metadata:
      annotations:
        service.beta.openshift.io/serving-cert-secret-name: maas-default-gateway-service-tls
    spec:
      type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: maas-default-gateway
  namespace: openshift-ingress
spec:
  host: {{ .hostname | default (printf "maas.%s" $.Values.global.wildcardDomain) }}
  port:
    targetPort: 443
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: maas-default-gateway-openshift-default
    weight: 100
  wildcardPolicy: None
{{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: maas-default-gateway
  namespace: openshift-ingress
spec:
  gatewayClassName: openshift-default
  {{- if .useRoute }}
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: maas-default-gateway-config
  {{- end }}
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      hostname: {{ .hostname | default (printf "maas.%s" $.Values.global.wildcardDomain) }}
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      port: 443
      protocol: HTTPS
      hostname: {{ .hostname | default (printf "maas.%s" $.Values.global.wildcardDomain) }}
      tls:
        certificateRefs:
        - group: ""
          kind: Secret
          {{- if .useRoute }}
          name: maas-default-gateway-service-tls
          {{- else }}
          name: {{ $.Values.global.wildcardCertName }}
          {{- end }}
        mode: Terminate
      allowedRoutes:
        namespaces:
          from: All
{{- end }}
{{- end }}
