apiVersion: maas.opendatahub.io/v1alpha1
kind: Tenant
metadata:
  name: default-tenant
  namespace: models-as-a-service
spec:
  gatewayRef:
    name: maas-default-gateway
    namespace: openshift-ingress
  telemetry:
    metrics:
      captureOrganization: false
