{{- range $user := (include "maas-code-assistant.users" . | fromJsonArray) }}
---
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: {{ $.Values.workspace.devworkspace.name }}
  namespace: {{ $.Values.workspace.namespacePrefix }}-{{ $user }}
  labels:
    {{- include "maas-code-assistant.labels" $ | nindent 4 }}
spec:
  routingClass: che
  started: true
  contributions:
    - name: ide
      uri: http://devspaces-dashboard.openshift-devspaces.svc.cluster.local:8080/dashboard/api/editors/devfile?che-editor=che-incubator/che-code/latest
  template:
    projects:
    - name: {{ $.Values.workspace.devworkspace.name }}
      git:
        remotes:
          origin: {{ $.Values.workspace.devworkspace.projects.repoUrl }}
        checkoutFrom:
          revision: {{ $.Values.workspace.devworkspace.projects.revision }}
    components:
      - name: tooling-container
        container:
          image: {{ $.Values.workspace.devworkspace.image }}
          sourceMapping: /projects
          env:
            - name: CHE_DASHBOARD_URL
              value: https://devspaces.{{ $.Values.global.wildcardDomain }}/dashboard/
{{- end }}
